[package]
name = "master-3-smoother-scroll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = { git = "https://github.com/stefnotch/rdev.git", features = ["unstable_grab"] }
